ok2cqr/cqrlog

src/uCWKeying.pas

Basically the TCWHamLib object must not go active until the OnConnect event fires. I have added the handling of this event as well as the OnError event in case something else goes wrong.
You may wish to handle similar handling of connection to the uRigControl and whatever else you have that uses TLTcpComponent. I think with the other things, you were just getting lucky that nothing was being sent until after the connection completed.
This PR, I hope you can use :+1:

Fixed connection refused error on hamlib cw

---

src/fNewQSO.pas
src/fTRXControl.pas

Filled in the CloseRigs function in fTRXControl.pas so that it will FreeAndNil the radio object.
This triggers the rig control destructor, which ensures that rigctld will be properly shut down, even if the TRXControl form is never opened by the user.
Added a call to CloseRigs when closing the windows manually in fNewQSO.pas to tie it all to the program's exit point.

close rigs even if fTRXControl is not showing.

---

src/fExportProgress.pas

If a QSL sent status with "S" was selected, the ADIF-export has produced
<QSL_SENT:1>N instead of <QSL_SENT:1>R

fixed: bug in ADIF export

---

tools/cqrlog.desktop

This allows use of custom icons and fixes some other issues.

Do not use a hardcoded icon name in the desktop file

---

Makefile
tools/cqrlog.appdata.xml

AppStream is a cross-distro XML format to provide metadata for software components and to assign unique identifiers to software. The metadata can for example be used by software centers like GNOME Software or KDE Discover to display a user-friendly application-centric way on the package archive.
This PR adds an AppStream AppData file.

Add AppStream appdata file

---

README.OH1KH
src/fMonWsjtx.lfm
src/fMonWsjtx.pas
src/fWorkedGrids.pas

Missing "All" checkbox.   See README.OH1KH at 08.06.2017 for details.
Added more colors to callsigns to tell about worked before status. See README.OH1KH (the end of it)

CQ-monitor:  More informative colors. Fixed missing 'All' checkbox. 

---

README.OH1KH
src/cqrlog.lpr
src/fMonWsjtx.pas
src/fNewQSO.pas

This (2.1.0-118 in my version count) has been running ok here and I have not received any bugreports from elsewhere either.
Still this does not completely resolve CPU load caused by richmemo when monitor has been on for several hours. There must be something in the units code itself.
Question1: Why we create so many forms at program start?
Some of them must be created, but some could be created only when/if needed. ( to decrease memory usage)
Question2: You use "InitCriticalSection" on several places. If I understood its function description right it should be initiated only once at main form. After that all critical sections should use that initilalization to completely halt any other parts of program running while code is in critical section. Am I wrong?

Changes to CQ-monitor:See README.OH1KH

---

src/fDXCluster.lfm
src/fDXCluster.pas

Shall we try this again once more?
Default height is 2px, so you never know it is there if you do not change height. (test compile and run as test user is done)
It is now long time tested and works ok. And it is handy if you use chatting when connected to telnet dxcluster. Otherwise it has no use, but does not do any harm either.
I have saved old .lfm and .pas files. 
If you say NO, I'll push them back (they will show up as new files on  next pull request, but there is no other way to roll back once done pull request, I have understood...)
----------------------------------
I have still queued:
-Wsjtx-CQ-monitor alert changes (needs some testing more before pull)
-Edited help-folder. I have moved chapters from my PDF to html for help-folder.
The folder content is little confusing, done …

DXChat now defaulting invisible

---

src/CHANGELOG
src/fNewQSO.pas
src/fXfldigi.lfm
src/fXfldigi.pas

- all remote loggings (fldigi, fldigi-xmlrpc, wsjt-x) keep "qso_dxcc" boolean false by setting old_call:="" and old_adif:=adif before save.
- wsjtx logging take start and stop times to log (before just stop time. UDP format changed since cqrlog 1.9.0)
- fldigi remote socket checking fixed (checked status after freeing socket, not ok)

Remote loggings fixes

---

src/CHANGELOG
src/fCWType.pas

Simple, but test it before release.
It should not break anything even if it was working for you with previous code, too.
Works here now ok.

Bugfix: CWtype/letter mode: a .. z double keying (while A .. Z were ok)

---

help/wsjt.html
src/fMonWsjtx.lfm
src/fMonWsjtx.pas
src/fNewQSO.lfm
src/fNewQSO.pas

New timer to switch higher polling rate for decoding near decode time starts. In FT8 mode there is just few seconds time to answer cq and almost all of that is needed for operator reactions. So decoding should happen as fast as can.
Best solution would be OnReceive event to fire decoding when something has arrived from UDP.
How ever this is not possible with Synaptic sockets (unfortunately) so only way is to poll by timer.
Other Wsmodes than FT8 do not need so fast reacts to UDP messages.
CQmonitor: "follow" line can be double clicked now and it loads Std messages but does not fire TX on Wsjt-x. Is is done with new UDP reply that exist in 1.9.0-rc3 version (and up).

Improvements to wsjtx

---

src/CHANGELOG
src/fWorkedGrids.lfm
src/fWorkedGrids.pas

Grid map did not load user digital modes to ModeSelector. Perhaps too early init (at form create) as they were loading ok to NewQso and QSO/Filter but not to grid map even when same dUtil routine was used for all.

Bugfix: Worked grids map: load user digital modes to mode selector

---

src/CHANGELOG
src/feQSLDownload.pas
src/feQSLUpload.pas

Because of changes before to wanted tab selection elsewhere eQSL up- and download preferences-button  did not open right tab.
This is because preferences.showForm last line sets now active page from public variable that is loaded from configuration file (Changed it when I made right tab open from DXCluster and TRXcontrol some times ago)
Now found this and it is also ok now.

eQSL up&dnload: preferences button did not open right tab

---

src/CHANGELOG
src/fNewQSO.pas

Nasty bug. Did not remember that wsjt-x remote can be run also without opening CQ-monitor (Who really wants it !?!)
This fixes only the Access violation bug, but is NOT completely same as I have in test binary 2.3.0-101. There are some other changes to this "sTx" routine too, but I want to see myself that they are working as I expect. So I need some days to play with them.
I'll do another pull request then for the rest of this part.
There are also in pull request queue (exist in TBin 2.3.0-101):
- fixed some text "realy" to "really" on several message boxes
- Exit & Autobackup: preferences,message box and help file text changes to clear out that this can also  prevent accidental program closing

Wsjt-x remote used nonexisting variable if CQ-monitor was closed

---

src/dData.pas
src/fDXCluster.lfm
src/fDXCluster.pas

Hi,
I added rudimentary Skimmer Support to Telnet DX Cluster. Two features were implemented:
1. Click in Skimmer Bandmap switches Radio to Skimmer frequency and sends call to NewQSO Window if call present.
2. If Skimmer decodes a spot and sends it to Telnet Client, A QSL check is performed to send back following state to Skimmer: 
DUPE	Worked this call on this band	Gray
NEWCTY	All-time new country	        Red
BNDCTY	New country on this band	Pink
NOTCFM	Worked but not confirmed	Blue
Open:
I didn't get the need for critical section due to the fact I'm fairly new to pascal. I may used it wrong.
Best regards,
Olli, DH2WQ

MErging PR Initial Skimmer Support

---

src/fAdifImport.lfm
src/fAdifImport.pas
src/fMain.pas

Some programs can only save single ADIF, without splitting by year or custom date range. Therefore date filtering is needed on the import side.

ADIF import: implement filter by date range

---

src/dUtils.pas

#114  the password for getting a hamqth session needs url encoding for special characters. using existing function EncodeURLData to encode password.

add url encoding for hamqth session password -fix #114

---

src/fDXCluster.pas

- Variable ThBckColor was not initialized in some situation
- Now DXCluster default Backgroundcolor is white
- case lotw and eqsl is given, lotw color will win

Fix the black background color bug in dxcluster gui

---

src/fMain.pas

In fMain.pas function TfrmMain.dbgrdMainKeyUp several sql statements uses the main dmData.qCQRLOG.SQL.Text to select a count().  the main data grid and all data fields like remark, etc. are not in the result set of the SQL-Statement, because count() only gives you one colum with a number.
fixed this point by separting the count-sqlstatements with dmData.Q1 and cleaning StartTransaction/Rollback/Open/Close.

fix second scroll down bug in qso list due to count SQL statments 

---

src/fAdifImport.pas

Did a quick test with ~7000 QSOs. Before it took about 6 seconds, now about 4.

ADIF import optimizations: avoid repeated ini reads and WriteLns

---

src/fCWType.pas

Passing ^ in CWType allows character combinations  (AR, SK ... ) to be sent when hamlib cw interface is selected.
Works only in word mode, not in letter mode. 
^ can be passed to CW macros and works there without any source modification.
This is tested with Icom 7300. May not work in other brand rigs.

Allows AR SK send with Icom/hamlib cw interface

---

src/dDXCluster.pas

- fix a IndexOutOfBoundException when reducing show-last-spot-station-number in xplanet reference.
- now it always delete the oldest entry, which is index 0.

fix IndexOutOfBoundException when reducing station number in xplanet

---

src/uCWKeying.pas
src/uRigControl.pas

I did find fmv from 2 places. As far as I can find out the vfo handling is not implemented anywhere . There seems to be some hidden vfo buttons at TRXConrol unused.
Polling vfo does not even work with Icom rigs causing just RPRT -11
I think we do not need it. Advise me if I'm wrong!

Remove vfo query: fmv -> fm

---

src/fMain.lfm

Unfortunately Qso list window had scaling problems. (Tnx to Giuseppe IKØDWJ).
I did never try it as fullscreen.
I feel also that lazarus is sometimes adding empty anchoring "allowed" checks by itself.
Perhaps proper way would be to set all lfm's to readonly state if no change to layout is planned while programming.

Qso list window scaling fix (anchors)

---

src/fDBConnect.pas

When exporting log preferences user may not understand that passwords, if set any, are in plain text format.

Warn plain text passwords in log ini files

---

src/fNewQSO.lfm

Giuseppe  IK0DWJ reported that SpeedButtons (eqsl,lotw,hamqth) have very narrow effective click area at top of button.
With my PC the active area is nearly whole size of button. Only at bottom is small inactive area. It seems to be depended on display size/resolution. Noticed same as Giuseppe when running cqrlog via vnc desktop.
When making a bit more room between and under of buttons seems to make effective click area wider in case it is shrunken.
This fix does not show up in any visible way between previous .lfm and this one. (actually shows, but changes are so minor...)

Room for speedbuttons

---

src/fLoTWExport.pas

- when a qso is logged with mode JS8 in the lotw adif export function the mode js8 is
replaced by <MODE:4>MFSK<SUBMODE:3>JS8. so js8 can now confirmed correct
- this is a workaround until the database is enhanced with field submode to implement adif 3.0.9

add workaround for js8 to have correct lotw adif upload

---

src/fMonWsjtx.pas
src/fNewQSO.pas

This fix detects wsjt type UDP message and rejects other UDP messages received from same port.
Follow callsign routine was not revised to newmonitor state and did not work at all. This returns it back to work.

fix: detect wsjt message, follow call routine

---

src/fAdifImport.pas
src/fMain.pas
src/fNewQSO.lfm
src/fNewQSO.pas
src/fPreferences.lfm
src/fPreferences.pas

New remote mode support for N1MM logger type UDP messages.
This allows only logging data transfers from programs like wsjtx, js8call and similars that are supporting  these kind of UDP messages.
NewQSO/File selection, or Ctrl+K to start remote.
There is no indication of logged qso unless user sets "Pref/newQSO/Show recent qsos" active.
Tnx to Andreas, DL7OAP, for help with this feature and fix of JS8 mode adif export as submode to LoTW.
With these cqrlog can now be used with JS8CALL program without problems.
Revised help files come in other pull request as soon as they are ready.

remote mode N1MM logger

---

src/cqrlog.lpi
src/cqrlog.lpr
src/uCWKeying.pas
src/uRigControl.pas

'v' is generating errors with Icom rigs, but Kenwoods can not survive without it. If 'v' is missing And Kenwood user pushes A/B vfo button from rig from panel cqrlog continues to show previous vfo frequency.
This is a rigctrl "feature" of Kenwood that it needs user action to poll current vfo before asking frequency.
uRigControl.pas is not suitable for fixing this easy. So we just leave errors for Icom as they do no bigger harm.
Added uRigControl.pas and uRotControl.pas to project. I can not see no harm with this. Finding them is now easier from unit list.

Returned rig polling 'fm' to 'fmv'

---

src/dData.lfm
src/dData.pas

Anderas, DL7OAP, made this upgrade coding. It is now tested and found working for upgrading existing log and creating a new one.
We have also already done several changes to other units to be used with this new version 16 database.
cqrlog_main added columns:
| contestname    | varchar(40)   | YES  |     | NULL    |                |
| stx            | varchar(6)    | YES  |     | NULL    |                |
| srx            | varchar(6)    | YES  |     | NULL    |                |
| stx_string     | varchar(50)   | YES  |     | NULL    |                |
| srx_string     | varchar(50)   | YES  |     | NULL    |                |
Names are self explaining
freqmem added column:
| info      | varchar(25)   | YES  |     | NULL    |                |
Info is for recording human readable …

Upgrade database to version 16

---

src/fMonWsjtx.pas

If previous line was directed cq prints cq direction also into my message line.
Common variable was not reseted after last use.
Happens very seldom, so was not found before.

Fix: wsjt monitor

---

src/fMonWsjtx.lfm
src/fMonWsjtx.pas

Small fix.
Doing trim+uppercase to edtFollowCall.Text every time it changes makes typing order of letters A .. Z have right-to-left order. Numbers have left-to-right order ! Strange!  Removed trim+upercase.

Fix CQmonitor follow call typing was right-to-left

---

src/dUtils.pas

sat_name.tab in tar file leads to cqrlog-cty.tar.gz downloaded at every start of cqrlog

add sat_name.tab and prop_mode.tab to lastupgradecheck.

---

src/dUtils.pas
src/fExportProgress.pas
src/fLoTWExport.pas
src/fMonWsjtx.pas

- ft4 sequence length was changed from 6 sec to 7.4 sec
- ADIF 3.1.0 is out > FT4 is SUBMODE of MODE MFSK
- LOTW ADIF upload works now correct
- correct ADIF Export (SUBMODE for FT4 and JS8)

fix ft4 new sequence length and ft4 as submode

---

src/dData.lfm

fix issue #38 using utf8_bin in create and mysqld-config 
- only changed the initial write of mysql.cnf in ~/.config/cqrlog/database

fix issue #38 using utf8_bin in create and mysqld-config

---

help/h24.html
src/fNewQSO.lfm
src/fNewQSO.pas

fix issue #166 DXCC list fails when qsl received field is filled wrong
- gui trims now qslr and qsls field when focus is lost
- update help24.html with the meaning of E (eQSL) and L (LOTW) in DXCC Statistic
- Hint: user is still responsible for entering valid qsl flags, garbage in means garbage out

fix issue #166 DXCC list fails when qsl received field is filled wrong

---

src/fMonWsjtx.pas

OK. This is fixed one. '>0' changed to '=1' to accept only USA at the beginning of line.
Sadly found out that previous reported South Korea as USA because of string "usa" was found in the middle of city name.

Fixed USA states remove from CQ monitor

---

src/fLoTWExport.lfm
src/fLoTWExport.pas

This fixes issue #173 when LoTW export window (upload Tmemo) size is so small that all text does not fit to visible part of Tmemo.
Keeps last line visible. User does not have to use scrollbar to see latest output.

Scroll upload window to last text line

---

help/h1.html
src/cqrlog.lpi
src/fNewQSO.pas
src/uVersion.pas

Fixes issue #188
This upgrade can now handle "binary garbage" in case normal wsjt datagrams are pushed to N1MM remote port and dig possible ADIF information (datagram nr.12) from there.
Qrz/HamQth info fetch waiting is improved.
Some information can also be entered to NewQSO during qso from where they are added at logging phase.
commit 845fff84c8de576ef5206f73c942c0f483ad4b52
Date:   Wed Aug 21 17:36:38 2019 +0300
Web info fetch works now. Some data for logging may also be written to NewQSO before logging
commit a75206199d3deff2b86ee1263f3e382f218b884d
Date:   Wed Aug 21 12:22:22 2019 +0300
Trying to make web fetch work, no luck
commit 90c82bddb5c0b3ae2e2f9a3e7b2e059202b06816
Author: OH1KH …

Upgrade for N1MM remote

---

src/dUtils.pas
src/fContest.pas
src/fGroupEdit.lfm
src/fGroupEdit.pas

Fixes issue #196 
Moved contest name selection list creation to dUtils (is now used by Contest and Group edit).

 Added 'Contest name' to group edit

---

src/fNewQSO.pas

This fixes issue #201
I did not notice it doing any harm elsewhere. Please check!
To test:
Add one club to preferences so that notice of membership is printed to AWARD field.
Uncheck NewQSO "Auto" checbox
Enter club member call to "callsign" field
Move cursor with mouse to "frequency" filed. You can move it directly or move with TAB to elsewhere and then come back to "frequency" field with mouse.
Then press 2x ESC. Call and everything else is removed but text stays in "AWARD" field. 
But ONLY if cursor is in the "frequency" field at the time 2x ESC is pressed.
--------
Making a breakpoint into ClearAll loop where all TEdits are cleared you can see that AWARD is cleared, but after procedure ClearAll  exits text is returned from somewhere to AWARD again.
(I did not dig the root cause …

Fixes award field clear

---

src/fImportLoTWWeb.pas

Now, I think, this fixes better LoTW download and QT5 problem.
At same go it reduces LoTW download status messages outlook a bit.

Fixed LoTW download messages. Works now with QT5 and Gtk2

---

src/fContest.pas
voice_keyer/IC7300_keyer.sh

During weekend SAC-SSB contest I noticed that it would be handy to have Ctrl-A (add to bandmap) to work also from Contest window.
It requires that call is entered to contest/edtCall and focus is moved to another field (I.E callsign is already copied to NewQSO/edtCall).
This is quite often the situation when low power station waits to get through a pileup. Then he can check other stations meanwhile. Useful for both CW and FONE operations.
Added a voice script that can be used (when renamed to voice_keyer.sh) with some new icom rigs (tested with IC7300) to initiate rig's voice recordings from cqrlog CW macro keys when using fone modes. Sends CI-V commands to rigctld using NetCat.

Add bandmap (ctrl-A) added to contest window. Voice out CI-V script

---

src/dUtils.pas

Fixes issue #212 .
Initates Result with loc.  Returns now empty string if loc is empty.

fixed function result

---

src/fMarkQSL.pas

fix issue #214 
user did have 'transaction already active' error when using auto mark. now, when starting a new query, the transaction is reset by a rollback.

fix issue #214 AutoMark QSL now always rollback transaction

---

src/fNewQSO.lfm
src/fNewQSO.pas

This fixes bug that is caused because JTDX udp frame #5 (logging) does not have all tags that are listed in WSJT-X udp format definition leaving the contest part of logging away.
Fix finds out from frame id that it is from JTDX and does not try to find contest tags then.
Other improvement is buffer pointer range check so that it cannot grow over buffer size. If buffer end is reached before all tags are decoded fetching them now results either 0 (zero) or '' (empty string). Or false in case of boolean.
This should help also other not standard udp messages received in future.
commit 758b76d95c2b647122563475d0d4b14a974bb8f4
Date:   Wed Oct 30 18:16:29 2019 +0200
A bit better pointer check
commit …

Fix for JTDX logging

---

help/index_right.html
src/cqrlog.lpi
src/fFilter.lfm
src/fFilter.pas
src/fPreferences.lfm
src/fPreferences.pas

This will fix calendar (TDateEdit) usage and allows to save filter with from_date and to_date empty.
Some clean ups for code creating the SQLfilter (btnOK pressed)
Version number update to help index page.
commit 48a290c44aa6bf6d9fe48c8e7aebf8e3d367d42d
Date:   Mon Dec 2 19:15:24 2019 +0200
cqrlog version to 2.4.0 at help index
commit d5227f8dabd8224c1cadde5a0651c1fb296eab59
Date:   Sun Dec 1 12:03:07 2019 +0200
Date fixes
commit 913649f18650be8aa629a486d241630594b18f98
Merge: 67d1330 e1d0d62
Date:   Sun Dec 1 10:56:38 2019 +0200
merged master
commit 67d13300acb1ef01f26825b2aea52d95ee859bda
Merge: 122db64 e9c4c88
Date:   Mon Nov 25 …

Filter do_date fix

---

src/cqrlog.lpi
src/fMonWsjtx.pas
src/feQSLUpload.pas

- Changes eQSL upload radio button selector texts by filter activated to make user understand better what is uploaded.
- CQ-monitor/follow: In addition to follow decodes by selected callsign follows also free text originated by selected call. This may happen if selected call is a special call or has extension /M /MM. The he can not show his location in CQ line but he can send a free text message for every now and then like "F5MYK/MM OJ12". Now follow copies line if follwed call is then first word and second word is qualified locator. It makes it easier to catch from all decoded results.
commit e0c4122832915d0215f209b3338facdf88fb0817
Date:   Mon Dec 23 13:01:05 2019 +0200
Change eQSL upload selector texts by filter
commit …

Fix eQSL upload selector texts and CQ-monitor follow addition

---

Makefile

This interferes with the packaging in Debian, and is hard to remove via
a patch because "clean" is invoked even when patches are not applied.
Specifically, it removes https://salsa.debian.org/debian-hamradio-team/cqrlog/blob/master/debian/cqrlog.install
(To remove debian/ artifacts at "clean" time, use debian/clean instead,
but shouldn't be needed as debhelper will clean up by itself.)

Don't remove debian/cqrlog* on clean

---

src/dData.pas

Issue #236 was not actually filter problem.
Distance counts in "qso list" window that were updated after setting filter did refer to cqrlog_main that really does not have column "dxcc_ref".
It appears as generated in "view_cqrlog_main_by_qsodate" that is now used instead of cqrlog_main and should fix this, and maybe other similar issues when filter is used.

Fixes unknown column dxcc_ref

---

src/cqrlog.lpi
src/fCWKeys.lfm
src/fCWKeys.pas
src/fCWType.lfm
src/fCWType.pas
src/fNewQSO.lfm
src/fNewQSO.pas
src/fXfldigi.lfm
src/frCWKeys.lfm
src/frCWKeys.pas
src/uCWKeying.pas

Common to all keyers:
F1 .. F10 CW-keys (from keyboard) works now if NewQSO, CWKeys or CWType window is active
F1 .. F10 keyboard auto repeat disabled (long keypress do not fill CW buffers)
CW is now sent only if rig mode (NewQSO/mode selector) is CW
Windows/CWType is not visible in menu list if keyer is set to "None" at Preferences/CW interface
Moving rig from other mode to CW sends "stop keying" (specially Hamlib/rig buffer may contain old morse in some cases)
Source code is cleaned up (removed duplicate blocks, etc.)
HamLib keyer:
Tried to make Hamlib keyer handshake better. Now messages up tp 10 characters are sent by one hamlib command,
longer messages are sent letter by letter.
Tested with WinKeyer and Hamlib keyer (Icom IC7300) modes. (I have no other keyers)
Squashed commit of the …

Some fixes to CW

---

src/fNewQSO.pas

Small code that allows adding bandmap call or dxcluster spot  to contest form's call column.
Actually makes call adding to new qso twice  if contest form is open (first add band/spot then take call from new to contest form and add it again to new qso) , but that simplifies code and seems to work ok.
This is not very deeply tested, but seems to work so far (tested in ARRL DX-CW running now).

Fill contest form call from 2clic of bandmap or dxcuster spot

---

src/fNewQSO.lfm
src/fNewQSO.pas
src/fPreferences.pas

This should restore the default behaviour. The DXCC tab is default. All other tabs hidden if sat mode is disabled. 
If sat mode is enabled the two tabs sat and lo config are shown. In this case default tab to open on start is the sat tab. 
@ok2cqr Hope this fixes our concerns from https://github.com/ok2cqr/cqrlog/pull/251#issuecomment-591363867

Only show LO tab if Sat mode is active

---

src/fPreferences.pas

This bug has been there for long. My fault not fixing it before as it was always seen and so easy to fix.
Depending from where the preferences was opened (NewQSO,DXCluster, TRXcontrol etc..) tab active was not in sync with left frame listbox item.

Sync left frame list and tab opening

---

help/h21.html
src/cqrlog.lpi
src/uColorMemo.pas

When DX spot is selected with double (left) click and DX callsign is set to NewQSO same time the info part of DX spot line is applied to clipboard.
User can then set cursor to a NewQSO field, like "comment to QSO", and press Ctrl-V to store the info (IOTA, SOTA, WWFF etc.) in easy way.
commit e643e3a1c72b6d434b36ffed3f1c6721c0e2fa06
Date:   Sun Mar 22 14:07:40 2020 +0200
removing debugs
commit c99de38846ab0550637ab4f470d06988562fa117
Date:   Sun Mar 22 13:41:19 2020 +0200
a bug fix
commit eea816e6e6d62f70cca3f1ca437e348fe2da5d86
Date:   Sun Mar 22 13:18:03 2020 +0200
Changed info copy to double(left)click and updated help file
commit …

Setting DX spot line info text to clipboard

---

src/fRotControl.pas

Visual fix.
Turn left, Turn right, buttons in RotControl did work when pressed without using stop button in the middle, but green coloring of previous direction button stayed on.
This fixes green to exist only in active direction button.
Pressing left/right now issues also first a stop command, waits a bit and then issues direction command.

RotorControl L > R > L buttons now works without using stop button

---

src/fRbnMonitor.pas
src/uColorMemo.pas

RBN monitor:
- Double click on empty monitor (I.E. opened but not yet connected, or empty because of filter settings) causes grid header text "Freq" to be placed as frequency to rig cat and NewQSO frequency column. Crashes as "Freq" is not a number. Now disabled if can not be converted to number.
UColorMemo (used in Band map and DXCluster):
-  Double click on empty memo causes crash as there are no spot lines to get info from. Now returns from getInfoFromSpot if 'vetp' (what ever it is? Seems to be line count, I guess)  is negative.

fix RBN,Bandmap,DXCluster 2xclick on empty view crashes program

---

ctyfiles/sat_name.tab

Add RS-44 to database. Corresponding with ARRL's recent update of tqsl's config.xml.

Add RS-44 to satellites

---

src/fNewQSO.lfm

Just noticed a typo in a tooltip when I moused over it. Hopefully it's easy enough to take this drive-by fix.

Tooltip typo: callsing -> callsign

---

src/fContest.lfm

Seems like the tab order of input fields has experienced some randomness :).
This re-orders the tabs into a sequence that makes sense in my eyes. Should the original sequence be intended feel free to cancel this PR :)

Re-orer sequence of input fields in contest mode

---

src/fMonWsjtx.pas
src/fNewQSO.pas

HI-speed decode periods are set to begin one second earlier. New version of wsjt-x 2.2.0 uses new 3 stage decoding. These settings makes cqrlog's CQ-monitor follow decodes faster.
K1JT:
FT8: Decoding is now spread over three intervals. The first
starts at t = 11.8 s into an Rx sequence and typically yields
around 85% of the possible decodes for the sequence. You
therefore see most decodes much earlier than before. A second
processing step starts at 13.5 s, and the final one at 14.7 s.
Overall decoding yield on crowded bands is improved by 10%
commit 4086283aec5169a2fe9c2ca357da85bdecdb5bbd
Date:   Fri May 15 14:39:05 2020 +0300
Changed period timers a bit
commit 501366c438d882ee2221c1e14d7e141826c31a11
Author: OH1KH …

Modified wsjtx monitor period settings

---

docker-build/Dockerfile

Seems like Ubuntu disco is not available anymore. My builds on eoan run fine though.
References: https://github.com/ok2cqr/cqrlog/issues/277

Update Docker image to Ubuntu Eoan

---

src/fChangeFreq.lfm
src/fChangeFreq.pas

For some unknown reason preferences/bands/frequencies/modify do not allow dot (or comma) for band Begin, End, TXoffset and RXoffset TEdit boxes when compiled with QT5 support. GTK2 compiled works OK.
All boxes in form have NumbersOnly:=true.  Middle line modes (CW,RTTY,SSB)  TEdit boxes do allow dot!
Tried even by deleting edtBegin TEdit box, then copying edtCW TEdit box and renamed the copy as edtBegin, but even the copy does not allow decimal dot input!
Assigned NumbersOnly:=false and added OnKeyPress that allows only 0..9 + , - ,dot , BS , Del
That works with both QT5 and GTK2

Numbers only does not work with QT5 in fChangeFreq

---

src/cqrlog.lpi
src/dSatellite.pas
src/fNewQSO.lfm
src/fNewQSO.pas
src/fTRXControl.lfm
src/fTRXControl.pas
src/fXfldigi.lfm
src/fXfldigi.pas

Satellite and/or propagation selection is cleared only from clear-button (at tab) or band change. Either manual, CAT driven (change from rig knobs), wsjtx or fldigi-xmlrpc remotes.
Having set propagation for example ES it was keeping there when logging qsos but as soon as one qso was cancelled (2xESC or new try with wsjtx) propagation was always cleared.
Now it is not and I think it is better this way. You can not always get qso that you have started to log in.
I do not work satellite qsos at the moment, but I believe that clearing satellite name has the same rules: only if band changes (then usually satellite changes too, I think).
Fldigi-xmlrpc and wsjtx remote frequency conversion is cleaned a bit.
Found interesting bug (cosmetic). If you have just one radio and the other is undefined …

Satellite and/or propagation clear

---

help/h20.html
src/fNewQSO.lfm
src/fNewQSO.pas

Removed some what randomly working red coloring from false locators.(Could not find a way to repeat wrong action).
Added check for typing input that forces to format AB12cd34ef. For remote received locator just first 4 upcase, rest lowcase filter (no num/char checks) exist.
Found undocumented shortcut Ctrl+F2 to clear NewQSO. Added to shortcut help.
commit ea1f51e44a0f8119e5c69d36ee21438375467c29
Date:   Thu Jun 4 09:32:30 2020 +0300
Comment change while testing
commit a791d4e9a62c5eaa5e18f3eb959901dee7f95c70
Date:   Wed Jun 3 10:05:49 2020 +0300
Removed edtGrid focusing and sometimes false working red warning color
commit f025106a5e354402e14b85adbbfaea8077cd40ba …

NewQSO locator column edit.

---

src/fDBConnect.pas

This fixes two errors in the sources reported by @dg0tm.
The first commit will cause an error on the first (re-)start of cqrlog because it cannot find the value for User as it was previously stored in "Logini" section due to a type.
The second was a useless if which did exactly the same in both cases.

Various fixes

---

src/dSatellite.pas
src/fNewQSO.pas

I added the propmode to wsjt-x logs and exports via UDP. This is the cqrlog end to also read propmode and log accordingly.
wsjt-x PR is here:
https://sourceforge.net/p/wsjt/wsjtx/merge-requests/6/

Also read propmode from wsjt-x

---

src/fFilter.lfm
src/fFilter.pas

Callsign is dominant in search and may cause empty results if having lonely space or some other not allowed char by accident.

Added check for A..Z,0..9,/ for filter callsign column.

---

tools/cqrlog.appdata.xml

Closes #299.
I have added screenshot that is already present in [README.md](https://github.com/ok2cqr/cqrlog/blob/master/README.md). Strict AppStream validator warns about the picture size, but it is just a warning and everything should work fine.
/cc @ok2cqr

Add screenshot to AppStream metadata

---

help/h1.html
src/fNewQSO.pas

-if wsjt address is set from 239.0.0.0/8 subnet UDP multicast support is enabled
Main purposeis that this allows multiple programs to receive decode information from one wsjt-x.
On the other hand multiple wsjt-xs can send information to cqrlog, but cqrlog can not handle multiple wsjt clients properly (maybe some day...)
commit 4094db2e5b7ce5b0a7c03cd4b460873d5eef2fb8
Date:   Thu Jul 30 17:27:04 2020 +0300
Some cleanup
commit fbd289e3bc5ddda5403a540d3220c0e65f7fdb0b
Date:   Thu Jul 30 16:24:11 2020 +0300
help update
commit c807ebe8367e333ef48cdb3f1903c1c57de1a25a
Date:   Thu Jul 30 11:22:29 2020 +0300
Adding UDP multicast feature to wsjtx remote if address is from …

Multicast support for wsjt-remote

---

src/fMonWsjtx.pas
src/fNewQSO.pas

Even when call is in parentheses (has another qso going on) and own TX does not start right away.
That allows to see information and perhaps previous qsos while waiting call's ongoing qso to finish and get own turn to make a contact.

Get info for call when 2click in Wsjt-Map

---

src/dSatellite.pas
src/fNewQSO.pas

This fixes false wsjt-x logging of propagation mode TR.
GetPropMode now returns empty string if no hit is found. That helps wsjt-x logging propmode that is a future implementation and does not yet exist in v2.2.2 (and JTDX 2.1.0) causing nonsense content of propmode that was leading to prop TR (last on the list).
Also if user has manually set propagation mode wsjt-x logging does not override it even when get proper propagation mode from wsjtx UDP message nr5.

Fixes false propagation 'TR̈́' with WSJT-X loggings

---

src/frExportPref.lfm

Checking "Most recent qsos first" at export causes ExAscTime to be true.
Then oldest qsos are on top of export:
ExAscTime   := cqrini.ReadBool('Export','AscTime',False);
if ExAscTime then
dmData.Q.SQL.Text := 'SELECT * FROM view_cqrlog_main_by_qsodate_asc'
Term "ascending order", "ASC", by qso date means rising date value that is "from oldest date to latest date".
Easiest fix is to fix the form text from "Most recent" to "Oldest". Then the text equals to source code and does what expoected.

Fix export order (ADIF/HTML)

---

help/h1.html
help/h20.html
src/fNewQSO.pas

For some unknown reason Details window opens from Ctrl+i and Ctrl+h keys. Also from NewQSO/Window/details where only Ctrl+i is mentioned.
Help file mentions that there is a checkbox in preferences/NewQSO to make Details open at program start. How ever there is no checkbox!
By default Details opens in fresh empty log, but once closed it keeps closed on next starts.
Change:
- Details opens from  NewQSO/Window/details and Ctrl+i
- Ctrl+h opens help
- shorcut keys help fixed
- NewQSO (sections: settings and operation) fixed

Details fix

---

src/fTRXControl.pas

If LO is active it also overwrites the RX frequency field with the LO QRG even in offline mode.
Setting this field should be ignored if we log offline.

Don't set RX frequency if offline mode is active

---

help/h20.html
src/cqrlog.lpi
src/cqrlog.lpr
src/dData.lfm
src/dData.pas
src/fAdifImport.pas
src/fCabrilloExport.pas
src/fChangeLocator.pas
src/fChangeOperator.lfm
src/fChangeOperator.pas
src/fEDIExport.pas
src/fExportProgress.pas
src/fNewQSO.pas
src/uADIFhash.pas

This adds support for (tempoarily) setting an operator callsign
via ALT+O. This is stored in a separate table column if it differs
from the configured station callsign.
I is exported to ADIF and cbr/edi files.
commit 4d9302d89ebc8d5f4f3fb0c891283310c9391e60
Author: phl0 <florian@florian-wolters.de>
Date:   Thu Sep 10 02:03:51 2020 +0200
operator support for cabrillo exports
commit ffed1b5a7cd61147305ee0afd15db4e0ce80f752
Author: phl0 <florian@florian-wolters.de>
Date:   Thu Sep 10 01:31:42 2020 +0200
Add operators to edi exports
commit 56ab0e5f36dfff54a8ffae05565344cb8fb717d5
Author: phl0 <florian@florian-wolters.de>
Date:   Wed Sep 9 16:36:06 2020 +0200
Retain operator call on QSO edit
commit db6d23109834c8258fa87e418c004dcb253e2235
Author: phl0 …

Support for separate operator

---

src/fExportProgress.pas

Add ADIF Tag BAND_RX like it is done for the normal FREQ and BAND Tag. BAND_RX is relevant for the qslshop.de when you want to send QSL cards for satellite qso's.

add ADIF Tag BAND_RX in ADIF Export

---

help/h1.html

It seems that cmds.StrictDelimiter := true does not work as it should allowing also space to be delimiter with the defined delimiter character then help file is changed so that user understands to use double quotes if his command string contains spaces between.
A Lazarus bug, perhaps?

Fix to DXCluster help

---

help/h26.html
src/uCWKeying.pas

Added limited support for speed changes in middle of macro text when using Hamlib keyer.
1) Version of Hamlib must be at least Hamlib 4.1~git Last commit 2020-10-20 03:22:59 2020 +0000 SHA=8a769c
2) Do not use space(s) between text and +(or -) rigctld will add them I.E. "TU+++599---001"
3) Speed change works only with BKIN mode (not F-BKIN) and at the moment new Icom rigs (tested only ic7300)
4) Test results for icom 7300: Macro string "TU+++5nn---001"
Speed 28WPM  +15WPM increase for "5nn"
Rig settings: TX delay 25ms, BKIN delay 7.5d, CW-Key set/Rise time 2ms
Measured time for 1st dot of "5" is 0.024sec,  2nd 0.027sec.
Speed change via CAT causes 3ms drop of first element. Not fatal!
With other keyers this existed already, but forgotten from help file.
Fixed help file.
Added speed limit …

CW macro speed changes with Hamlib keyer

---

src/fClubSettings.lfm
src/fNewQSO.pas
src/fRebuildMembStat.pas
src/uVersion.pas

1) fixed a bug in Club marking fied selection that I myself had done when trying to make "comment for qso" look similar in all places. At membership settings it must be named by the DB column name "remarks" (that may confuse user) so returned it to that.
2)QSO list/Statistics/Membership tracking/Rebuild membership statistices is fixed. It did set all empty marking fieds filled with club (first club's if several) mark. Now sets just ones that really are club members.
Thanks to Andreas, DL7OAP, who saved lot of my time suggesting fix. Otherwise I should have learned myself (better) for sql join to find out what is the root cause.
commit e3d93ae52ec9b1444e1dac47eef61b1810c2d1dc
Date:   Fri Oct 23 10:11:01 2020 +0300
Version date …

Fix for Club membership

---

src/dDXCC.pas
src/fCabrilloExport.pas

After taking part in CQ WW I discovered that the cabrillo export had some issues. The field SPECIFIC does not exist.
Also the field "country" is not filled correctly. It was always showing the country of the last logged station instead of the one of the operator.
And the "POSTALCODE" field had one hyphen too many.

Fix cabrillo export

---

src/fNewQSO.pas

If you have master log without QTH profiles and you ADIF import portable logs that have one or several QTH profiles defined those profiles are added to master log during import.
Then if you view or edit imported qso that has profile set with different locator than master locator that is changed to NewQSO (bottom left) and when you close view or edit that locator remains, although QTH profile selector becomes empty.
There is no other way than feed the master locator again with Ctrl+L or restart cqrlog.
This fix sets locator from proferences/Station if NewQSO/QTH profile selector is selected as  empty, or cleared by return from View or edit.

Fixed My Loc setting with multiple QTH profiles

---

src/fQTHProfiles.lfm
src/fQTHProfiles.pas

Button 'Edit' not enabled if profile count is zero. If it is used when count is zero edited profile save causes either SQL error or is just not saved anywhere.
QTH profile gird has now autosize columns for easier read.

QTH profiles editor fix

---

src/cqrlog.lpi
src/fCWKeys.pas
src/fMain.lfm
src/fMain.pas
src/fNewQSO.pas
src/fRemind.lfm
src/fRemind.pas
src/fWorkedGrids.lfm
src/fWorkedGrids.pas

Several forms fixed so that if active 1xESC will return focus to NewQSO/edtCall.
This has been default action as most of forms already act this way.
In addition return to NewQSO/edtCall is fixed so that if Contest form is active return to Contest/edtCall is made instead.
Form fRemind was not part of project. Added to project.

Fix 1xESC keys

---

src/dUtils.pas

Importing ADIF QSOs failed if only band is set and frequency is absent. In this case TdmUtils.FreqFromBand would return 3500 MHz for 9cm band. This frequency is invalid as 9cm band is 3400 to 3475 MHz per definition / band plan.
This PR adjusts the frequencies returned by the aforementioned function so that the SSB/CW activitiy frequency is returned and ADIF imports of GHz bands works.
This patch has been tested and confirmed by @dh5ym.

Fix GHz bands (and ADIF import) 

---

src/fPreferences.lfm

Rigctld has mode setting option "0" that means use default bandwidth.( M USB 0 )
That is mentioned in man pages.
What is not in man pages (until now) is that option "-1" is accepted too without errors. It means "No change". (WSJT-X program uses that, so it can be there for all rigs)
Not all rigs support this, but as some do it must be possible to enter also "-1" to preferences/modes/bandwidths
Fixed MinValue of bandwidth edits to -1

Fix to modes bandwidth

---

src/fGrayline.pas
src/fWorkedGrids.lfm
src/fWorkedGrids.pas

Grayline:
popup menu "Link" were not enabled properly in all cases.
Uncheck popup menu "Link" was not possible if proferences had this property checked
Grid map:
Focusing bandselector at startup caused looping at certain cases. Return to newQSO with ESC seems to work now without it.

Bugfixes to Grayline and Grid map

---

src/fNewQSO.pas

Just had longer CW qso and noticed that "QSO takes" line rolls under Comment to callsign edit field when minutes and seconds have two digits.
Using just hr, min and sec will make the string short enough without loosing information.

Ultra small fix to NewQSO

---

src/fMonWsjtx.pas
src/uVersion.pas

Change to wsjtx remote parameters. This seems to be better.

Fix wsjtx timer parameters

---

src/fDatabaseUpdate.pas
src/fMain.pas

Some users report that execution stops when running it. I have found same, but randomly. It may crash whole Xwindow system and it needs to be killed via terminal (Ctrl+Alt+F2) login.
Things that I have found out and can be repeated happens like this:
Take a test log.
Make filter that select few qsos
Use group edit to drop all names from them (to see better what database update does)
Go to Callbook/Database update and let it run.
1) It always updates only the last qso from selected qsos, nothing else.
2) If Database update has been cancelled at last time it stores the last id.
How ever if qso selection of current filter does not contain that qso id
update gets lost and window does not close from "Cancel" button.
These are now tried fix, but storing the cancelled updates last id is not good …

Callbook database update fix

---

src/fNewQSO.pas

Prop mode gets cleared after logging a (SAT) QSO. For some unknown reason the last prop mode is unset while saving. 
This patch circumvents this problem. I think it is useful to retain the prop mode until it is manually set to something else.

Retain prop mode after saving (SAT) QSOs

---

src/fDBConnect.pas
src/fDXClusterList.pas
src/fGroupEdit.pas
src/fMain.pas
src/fQTHProfiles.pas

As described in https://github.com/ok2cqr/cqrlog/issues/364 CQRlog executes critical operations even though the user presses ESC in the dialog box asking for YES or NO.  So if the program is asking if you really want to delete the database or a QSO and one presses ESC to cancel the process the critical operation is still executed. This is the opposite of what a user expects.
Also YES is the pre-selected button in those dialog boxes. I guess it should be 'NO' per default and force the user to explicitely select 'YES' to confirm.
This addresses issue https://github.com/ok2cqr/cqrlog/issues/364.

Prevent execution of critical operations my pressing Esc

---

src/fNewQSO.pas

I was contacted because the DX spots that can be created from CQRlog obviously set my grid and the DX station's grid in wrong order. Subsequently some DX info collection tools fail to parse or parse with incorrect data. 
The concrete question arose on Twitter: https://twitter.com/SpaceStation22/status/1341377735361486848?s=20
The full thread is here: https://twitter.com/SpaceStation22/status/1340998770402717699?s=20
After reading on DXluster message it seems my grid and DX station grid just need to be exchanged. This patch implements that.
In this case my grid (JO31ol) stands before propagation mode and UA3XCR's grid follows. This seems to be the correct pattern.
Evidence is welcome :)

Exchange my grid loc and DX station's grid loc

---

src/fNewQSO.pas

Locator order was fixed in #368 .
That affects to spot created from call that is in NewQSO.
If new QSO is empty and spot is created from last logged qso the order is upside down.
This fixes also that part.

DX spot locator order fix

---

src/fNewQSO.pas

I discovered from @OH1KH 's PR https://github.com/ok2cqr/cqrlog/pull/374 that there is also a function for DX cluster spotting after logging/saving the QSO. I did implement a function to optionally spot the RX/downlink frequency with https://github.com/ok2cqr/cqrlog/pull/251. This should also be applied to the "post QSO spot" function I guess.

If "spot RX" is set also use it for post QSO spots

---

src/dQTHProfile.pas
src/fChangeLocator.pas

I guess that QTH profile numbering is meant to start from 1.
How ever sql sentence "select max(nr)+1" does not work if there are no profiles. Max(nr) generates NULL and addition NULL+1 results to NULL.
If we just take max(nr) and then later produce "AsInteger" then we can add +1 and in case of NULL AsInteger results 0 and addition +1 to that results to 1 what is expected.
If temporary locator editor (Ctrl_L) is left empty station locator from preferences is copied at close with OK. This is easy way to restore locator back to base setting.

QTHprofile numbering and temporary locator fixes

---

src/fNewQSO.pas
src/uCWKeying.pas
src/uVersion.pas

Winkeyer init fails leading to defunct speed change and stop (by esc). Issue #377
I could not find error from code. But increasing delays (50ms) at init procedure to 300 ms seems to fix init and when it passes OK everything works.
Changed CW init from newQSO start. It is not needed there because rig init inits also CWkeyer.
Exeption is that when user denies keyer init when switch radios, then init must be done at newQSO start (to be done at least once).
Added fActive check to winkeyer send text routine. It was not there allowing text send even when winkeyer init failed. Now does not send text if init failed.

Fix for winkeyer

---

src/fAdifImport.lfm
src/fAdifImport.pas

Found out that duplicate check checks just date+time+callsign.
That is wrong as in real life you can have (specially in contests) two qsos that may be logged as same date and time (within one minute).
Taking account of those qsos we have to make duplicate check for date+time+callsign+band+mode to find real duplicates. That is fixed to sql query.
Added date+time+callsign+band+mode line to question splash that asks about importing duplicate.
Fixed ADIF import form layout and anchors and made filter count depend on checbox filter by date.
Changed "complete!" color from red to green as red usually informs about error, warning or forbidden situation.
FYI:
My test adif had 19814 qsos with 201 frequency errors (region2 adif import to region1 cqrlog) and 2 duplicates (after fix was done, several …

Fix for ADIF import

---

src/fConfigStorage.pas
src/fNewQSO.lfm
src/fNewQSO.pas
src/uMyIni.pas
src/uVersion.pas

- MyIni function LocalOnly checked sections+comma from localsections list. This led to situation that always last section was ignored because it did not end to comma. Fixed to check the section names without comma.
- fldigi/wsjtx section did not include "ADIF" IP and port (former "n1mm" as named in config file). Added that.
- removed two empty actions from NewQSO form that were added there by accident when editing PullRequest #385

Fixes for local settings

---

src/fNewQSO.lfm
src/fNewQSO.pas
src/uVersion.pas

- fixed all my mistakes in PR #385. I do not understand how that code passed testing. Now Edit and View should work ok.
- removed qsl, eqsl, lotw confirmed labels.
- added them all appear to DXCC info Tedit box. It is actually kind of DXCC information. Activated auto scrollbars in case there will be more lines than fit.
- added band info to confirmed lines. It always shows first found qso information with callsign. Good or bad? If many qsos with callsign should confirmation refer to current band, or should it be combination of all qsos confirmed (if confimation differs by bands)?
- reordered/placed date,start,end, offline and qso takes as now there was more space.
- fixed edit qso to set offline. Otherwise qso date/time was changed at save. How I have feeling that Edit did set offline ON …

Fix for NewQSO: Edit and View error

---

src/feQSLUpload.pas

- removed password encode url from eQSL upload. When username and password are placed in uploaded adif file header part as tags encoding special characters is not needed and leads to wrong password.
Tested with <EQSL_PSWD:9>Saku!_<>: that did work both down and upload that proves urlEncode is needed only in download where password is included in URL.
In upload it is placed in adif header where encode is not needed and plain text accepted.
How ever password can not contain special UTF-8 characters. Only one byte ascii up to 0x7E can be handled by cqrlog. And I suspect the same with eQSL server.

Fix for eQSL upload

---

src/dData.pas
src/uVersion.pas

This fixes bug (long lasting) with UTF-8 that appears with Laz2.0.10/fpc3.2.0 but has been lying there already before. (issue #323)
This makes old qsos special characters "garbage" when they were saved with program compiled with fpc3.0.4 or earlier.
That is why I do NOT expect this pull request is ACCEPTED !!
This is just to show how things must be, and for testing.
This problem needs further thinking how this is implemented with minor trouble for users.

Bug fix for UTF8

---

src/fNewQSO.pas

if NewQSO previously worked qsos list (on top) was empty right click activated popup menu that tried to find qQsoBefore fields. ( https://www.cqrlog.com/node/3113 )
-  Disabled that and also disabled all popup menu items if qQsoBefore is empty.

Fix for show recent qsos before popup

---

src/fNewQSO.pas
src/uVersion.pas

While fixing just date/time change when old qso was edited made a new bug that resets Offline checked when New Qso is saved in situation where Offline is set manually I.E. no rig CAT control in use.
This should now fix both. Keep manually set Offline on and set Offline while old qso edit.

Fix for NEwQSO/Offline

---

src/fBigSquareStat.pas

Compile with Laz2.0.10/fpc3.2.0 or with laz2.0.12/fpc3.2.0-1 cause runtime Access violation in Big square statistics. https://www.cqrlog.com/node/3123
When older Laz/fpc is used this error does not exist at line 177: db.post of fBigSquareStat.pas
Got some help from Lazarus forum and modified it little bit further. Result seems to be again similar compared to result with old laz/fpc compiled version result without Access violation errors.

Fix for Statistics/Big squares

---

src/dUtils.pas
src/uVersion.pas

Fixed empty RegExp error that happens in qsl label printing when cqrlog is compiled with freepascal ver > 3.0.4

Fix for qsl label printing.

---

src/fExLabelPrint.pas

Upon exporting QSOs for label printing that have grids with more then 6 chars, CQRlog throws an exception because the loc fiefd in temporary qslexport table is only VARCHAR(6):
This shortens longer locators to 6 chars to that the export works again.

Shorten grid to 6 chars for label export

---

help/contest.html
src/fGroupEdit.pas
src/uVersion.pas

- Group edit informs after execution WhereTo the change was made.
Also "Cancel" button changes caption to "Close" as the change that has been  done cannot be cancelled, only Group edit form can be closed.
"Close" turns back to "Cancel" if field or value is touched after Group edit operation.
- Help file for "Contest" window has fixed. I hope it is now more informative and at least Cabrillo support is now properly mentioned.

Small fixes

---

src/fPropagation.pas
src/uVersion.pas

When propagation/solar data is defined to show out as text there are sometimes
situations that no data is shown. On next day problem is away.
Found out that if downloaded solardata.xml (as solar.xml in cqrlog directory)
has node(s) without data try loop fails to loadxmlfile because data is
assigned, but there are no (0) first.child to load.
Added check that assigned data has also ChildNodes.Count > 0
Helped to view values today when "fof2" node was empty. So I guess it is ok
to test also with other nodes loaded.

Fix for propagation

---

src/dUtils.pas

QRZ xml api connection strings have been changed to use HTTPS. QRZ's legacy http xml api sends the initial connection string username and password in the clear over the network as identified by packet captures. 
The api version number is also declared as part of the connection string to ensure future changes to the api do not break cqrlog.

Fixed security vulnerability with legacy qrz xml api

---

ctyfiles/sat_name.tab

A few new SATs available that are missing in CQRlog's sat_name.tab.
To keep it in sync with LotW I wrote a small script that extracts this data to sat_name.tab. This way LotW uploads should work without issues. If needed I can also provide the script itself.

Update sat_name.tab from tqsl config

---

src/fDXCCStat.lfm
src/fDXCCStat.pas
src/uVersion.pas

Complete layout fix, no code changes.
**Goal_1:** To make Wkd/Cfm Grid vertically autosized to see all 10 rows all the time without the use of vertical scroll bar. I think this is the main interest grid.
Status by countries/bands grid is big and needs scrolling anyway.
**Goal_2:** To fix PHONE group box anchoring so that CWM line does not drop over bottom border line with QT5 widgets.
Renamed lfm components (for easier location during pos/anchoring)
Redesigned positions and anchoring
Added W/C_Gird constraints.minheight setting by font size in form show procedure. Tries to keep all 10 rows visible without scrolling.

Fix for DXCC status form

---

src/fContest.lfm
src/fContest.pas
src/fNewQSO.pas
src/uVersion.pas

After SAC CW 2021 following fixes needed:
- initial size was a bit too small hiding some checkboxes
- position and size saving works now also when cqrlog (NewQSO) is closed while contest form is open
- added CW speed indicator to right side of contest name combo box
- CW contents are now fetched from contest window (previously from NewQSO)
That makes macro %c (callsign) work also when parital call is written. I.E. can send partial call to ask the complete call.

Fixes to Contest

---

help/fldxml.html
src/fCabrilloExport.pas

-Fixed Cabrillo Reject log QSO format to be same as in Cabrillo export file.
-Added reject reason in front of every rejected qso line
-Graphics fixes:
-- "overwrite existing file" messagebox did not clear up after answering Yes or No
-- Progress bar did not update when using GTK2 widgets
-Tried to clear Fldigi xmlrpc help at "drop after sync error" part.

Fix to Cabrillo export and fldixi xmlrpc help.

---

src/cqrlog.lpi
src/uCWKeying.pas
src/uVersion.pas

Fixed hamlib CW to work if rigctld was started with parameter "--vfo"
or without it.
Fixes issue #450
commit ce9ffa3dbca36d4184561c13ccade84ef4fbdcdf
Date:   Thu Oct 14 20:03:47 2021 +0300
Small changes and then testing. Seems to be ok now
commit 5b7e56bdbd99d04a29f0a29ceccc44d432bd47a9
Date:   Thu Oct 14 14:36:34 2021 +0300
set speed works now. Need still testing
commit f0db148a6c309b706d22005c94d1a498f5c70950
Date:   Thu Oct 14 12:20:58 2021 +0300
starting to fix hamlib cw when '--vfo' is used

Fix for Hamlib CW

---

src/fAdifImport.pas
src/fExportProgress.pas
src/uVersion.pas

-fixed adif export submode exeption OLIVIA. Fldigi remote saves mode
with "name-bw" while standard uses " "(space) instead. Replace "-"with " " done.
There are more BWs in fldigi/olivia than standard. Now passes them all to submode.
Noted that while fldigi shows modes in unstandard way (that is then transferred
via remote xmlrpc to cqrlog) it writes its own adif export in stadard form (!!)
-import will now place all submodes to mode ( issue #448 ) as there is no
submode column in cqrlog's database. If submode is passed to mode lockSubMode
is set in case qso record has mode and submode tags in reverse order.
Lock is cleared on qso record save.
commit d47e118ae1c02d97bc5edf27c265e2826f7933cc
Date:   Fri Oct 15 09:54:24 2021 …

Fixes to adif import/export

---

src/dData.pas
src/dUtils.pas
src/uVersion.pas

dmUtils.FreqFromBand was hard coded to return frequency when band and mode was given.
How ever it had a typing error with 60M band that caused LoTW import fail with that band.
As hard coded errors are difficult to fix frequency lookup is now moved to cqrlog_common.bands
where user can edit values via preferences/bands/Frequencies.
For more information see issue #457
Created update to version 5 for cqrlog_common. Added 3 microwave bands.
commit ea685a68439758979b214be24b9d42a663bc6e71
Date:   Tue Nov 16 15:33:31 2021 +0200
Added missing 3 microvawe bands to cqrlog_common.bands by database version update to 5
commit d70345c18456f11cce03a0f4abf419f234aa3fd9
Date:   Mon Nov 15 21:17:37 2021 +0200 …

Fix for dmUtils.FreqFromBand

---

src/fAdifImport.pas
src/uVersion.pas

Fixed adif import when date filter is used. If qso was rejected by date the typevariable was not initialized before next qso.
Thanks to N3GB for reporting the bug.

Fix for adif import with date filter

---

src/fContest.pas
src/uVersion.pas

Fixed 1st ESC to return cursor at the end of callsign without selecting any text. Now adding suffix to partial callsign can continue after 1st ESC right away.

Fix for Contest

---

ctyfiles/sat_name.tab

Add new SAT to be launched. See
https://amsat-uk.org/2021/12/18/xw-3-cas-9-launch/

Add XW-3 (CAS-9) satellite

---

src/fNewQSO.pas

- Set "Save QSO"-button disabled and disable saving by ENTER
when any of remote modes are active.
For every now and then someone (not reading help) gets in trouble
when saving remote qsos with button or enter.
All remote modes trigger saving without user intervention and so
enter and button can be disabled while in remote mode.

Fix to remote saving

---

src/azidis3.pas

When exporting the EDI file there are sometimes a minor error in the distance calculation. The reason is that the function used do a round of the QRB calculation.
According to IARU-R1 VHF Handbook chapter 5.9.1, page 165, "For the amateur bands up to 10 GHz inclusive, points will be scored on the basis of one point per kilometre, i.e. the calculated distance in kilometres will be truncated to an integer value and 1 km will be added."
However this easy fix might have unwanted side-effects as the calculation is used elsewhere. If this can't be accepted a different function for "started kilometer distance" should be added.
Is it needed two have two different QRB calculations? One rounded and one "started kilometer".

Corrected the QRB calculation to be right for REG1, see /node/3292

---

src/fEDIExport.lfm
src/fEDIExport.pas

As it is now mode code '0' is exported for a QSO when there is no match between the TX mode and the standardized TX modes in IARU-R1 VHF Handbook page 94. This is in line with the standard. But the mode code "7" a.k.a. "RTTY - MGM" (MGM = Machine Generated Mode) is a generic TX mode for all digital modes like FT4, FT8 etc.
Given that there are new digital modes created literally every day a way of mapping these digital modes to mode code "7" would be beneficial. My proposal below proposes a field and when the TX mode matches that field the mode code "7" is used.

dded support for exporting digital modes correct, /node/3293

---

src/fExportProgress.pas
src/uVersion.pas

Fixed BAND adif tag data to have lowcase "m" by adif standard.
https://adif.org/312/ADIF_312_annotated.htm#Band_Enumeration
If cqrlog adif is imported to program that uses stright adif standard
without exeptions the band uppercase "M" causes problems.
It is vice versa as in pull request https://github.com/ok2cqr/cqrlog/pull/482
where lowcase "m" caused problems to cqrlog.
Making export with "m" and accepting both cases in import should make everyone happy
It can cause problems if cqrlog exported adif (with this version "m") is imported
to older cqrlog. But I expect this kind of case happens more seldom.

Fixed ADIF export

---

src/fExLabelPrint.pas
src/uVersion.pas

If there are qsos that are imported from another program they may not have
QSL manager information. It is not added in adif import process even when cqrlog's
manger database has the information.
Normally this does not show up to user because if the qso is viewed or edited QSL manager information is fetched from database. In case of just view qso user may think manager info is OK.
How ever it is saved to qso record only when editing qso.
When user prints QSL labels they are then printed without manager info.
This fix checks QSL manager, and if empty, tries to find one from cqrlog's mgr database. If valid mgr is found it is added to QSL label, but not to original qso record keeping it clean.

Fix to label printing

---

help/h1.html
src/dLogUpload.pas
src/dUtils.lfm
src/dUtils.pas
src/fAdifImport.pas
src/fCabrilloExport.pas
src/fDbSqlSel.pas
src/fEDIExport.pas
src/fExportProgress.pas
src/fImportProgress.pas
src/fLoTWExport.pas
src/fMain.pas
src/fNewQSO.pas
src/fSOTAExport.pas
src/fXfldigi.pas
src/feQSLUpload.pas
src/uADIFhash.pas
src/uVersion.pas

This fix does not affect "classic" modes CW,AM,FM and SSB that already has had conversion from USB/LSB to SSB.
How ever there are hundreds of submodes in adif standard.
IMHO the idea of mode and submode is not very clever. I would like to see all submodes
to be modes, and then then there would be modegroups instead.
This way mode would be mandatory information and modegroup just makes genres of them if that is needed for awards or other kinds of grouping.
But we have to live with this. This fix makes conversion from mode+submode to "CqrMode"
that mainly is submode in ADIF standard. How ever there are some exceptions.
A part of submodes are "for import only" by ADIF standard. They should be accepted in
import, but never exported. It seems that at least eQSL does not follow that standard …

Fixes to mode/submode handling

---

src/fAdifImport.pas
src/fExportProgress.pas
src/fLoTWExport.pas
src/feQSLUpload.pas

Added one linefeed before first line of adif header.
This makes linux command 'file' to detect adi files as text
instead of music file.

Fix for adif headers

---

src/fRotControl.pas
src/uVersion.pas

Turn left/right buttons did not keep their visible state over Cqrlog restart. Reported by Mick, MI0HOZ
Fixed

Fix for ROT control

---

src/fNewQSO.pas
src/uVersion.pas

Revised PR #503 
As it seems to be adif.org/"sponsor defined code format" to add comma 
separated state as prefix to county name we accept that.
But, at least with non payed QRZ accounts, some calls like W1AW show out
without county then state prefix may not be added to empty county name.
Fixed that.
commit 9c794672350702d5dbad53070ee42aa4934e5e78
Date:   Thu May 12 11:18:12 2022 +0300
Fix for county storing
State prefix may not be added to empty county name.
commit 5e3f35a13f8c81d4eb0484c4e19df48e65198f49
Date:   Tue May 10 12:46:06 2022 +0300
Fix to county storing
What is the mind of adding state to county and then storing that?
It just duplicates the information because state exist in state …

Fix for county storing

---

src/fBandMap.lfm
src/fDXCluster.lfm
src/fDXCluster.pas

Changed hardcoded white background in DXCluster and BandMap to Default Color. Used theme-dependend clWindow and clWindowText for Item Colors.
PLEASE TEST BEFORE MERGING
This fix does have some unwanted sideeffects:
1) First line in DXCluster is Black, Don't know why.
2) Lines at the end of each item
3) Contrast of items is low (should't be: clWindowText should be inherited from Theme and match contrast with clWindow)
3) Aging colors don't seem to work with that fix. That's a real blocker.

Changed DXCluster Colors for Dark Mode

---

src/lnet/lib/lclnet.pas
src/uVersion.pas

With these small fixes Cqrlog compiles with Gtk3 widgets.
How ever running compiled program causes several widget errors.
You can see similar errors with Gtk2 if Cqrlog is started from
console. Difference is just that Gtk2 errors do not kill the
program like it happens with Gtk3 widgets in use.
So this is just a start to gtk3 and (lot of) work needs still
to be done if one wants to use Gtk3 widgets with Cqrlog.

Using GTK3

---

src/fAdifImport.pas
src/fCabrilloExport.pas
src/fCallAttachment.pas
src/fDbError.pas
src/fEDIExport.pas
src/fNewQSO.pas

The feature for checking your EDI file when it has been created
will not open all filenames / paths.
The failing files / paths are those with one or more spaces in them.
The remedy is to quote the string. The same error exists in
the Cabrillo export as well.  (#517)

Fix for opening certain filenames in the EDI file export.

---

src/fTRXControl.pas
src/uRigControl.pas
src/uVersion.pas

MI0HOZ reported that his rig closes ok from TRXControl P-off button
but does not start from P-on button.
I did know this before but always thought that it was my IC7300 "property".
More careful testing did show that it is Cqrlog's bug.
If rig power off or stby  button is pressed and rig closed
Cqrlog continues polling. That stacks commands/responses and
when Power on button is pressed command is sent to rig but it may
take several minutes before action.
This showed up totally new problem.
Cqrlog "just throws out polling" to rigctld and assumes that there will be proper
answer on return.
How ever the code does not wait for return, it continues polling by timer
even when there is no answer.
It should not do so.
For every command sent to rigctld there should be always some kind of reply …

Fix for rig power on

---

src/fNewQSO.pas
src/uVersion.pas

This fix will add simulated Ctrl+Home keypress after QSO list
is refreshed.
It happens only when "refresh data after save qso" is checked
and moves selection on top of the log to view last saved qso.
It does not affect QSO list selection point when QSO is saved from
EditQso.
commit 804314833a47198288063c56ce9c4c0c02ac58d0
Date:   Mon Jul 4 14:41:16 2022 +0300
This is even better. Does not effect qso edit, just new qso
commit 3e67a21518a707dc3bd605359c4426cd2495b7af
Date:   Sat Jul 2 13:09:08 2022 +0300
Another way, only when save. Is this any better?
commit 83138e6042ac3c9d92b873c33284cefdf3e13fa9
Date:   Sat Jul 2 12:25:24 2022 +0300
Fix for qso list
Added simulated …

Fix for QSO list

---

src/fRbnMonitor.pas

During high traffic (IARU HF contest) it suddenly showed up
that either editing filter or disconnecting monitor caused
error message (Abort/Ok).
By debug assembler the error happens in thread close section.
Found out that RBNThread has FreeOnTerminate set True and
procedure acTerminate first terminates thread and then tries to
FreeAndNil it.
This looks like double free for me and tried to set
FreeOnTerminate :=False and problem disappeared.
I am not quite sure is this true effect or just some other
thing changed.
Anyhow it should not do any harm this way, I think.
When this kind of problem apperars it also (but random) leads
to Cqrlog starting problem when it dies at start.
This happens at NewQSO/FormShow where ShowMOdal (of DBconnect) seems
to produce mrOK:=false condition.
After several …

Fix for RBNMonitor

---

src/fNewQSO.lfm
src/fNewQSO.pas
src/uVersion.pas

When Offline checkbox is checked and first qso typed in and saved
focus will return to QsoDate column instead of Callsign column.
Then when date, start time and end time are set and then TAB
pressed focus will move to callsign column.
This happens only if callsign column is empty (not when in edit qso)
This makes qso manual feed from paper log easier as things start
from date and tabulation continues in chronological order:
date,start,end,call,freq, mode .. etc and when qso is saved
focus returns again to date column.
When typing in Date and times in Offline Cqrlog will add punctuation
marks ('-' or ':') automatic. This way only number keys need to be typed.
When not valid locator is entered (usually odd number of characters)
NewQSO/GRID label will turn bold red as warning sign when exit …

Fix to QSO offline input

---

CHANGELOG
Makefile
src/changelog.html
src/fMain.lfm

Make it easier to install cqrlog into /usr/local (or elsewhere) with correct sub-directories.
Also fixes QSOlist display for dark themes

Allow installation to /usr/local or ~/.local

---

Makefile
tools/com.cqrlog.cqrlog.appdata.xml

This PR makes the CQRLOG AppStream metadata more modern and accepted by current parsers.
Important changes:
- Remove my _copyright_ comment.
- Use proper rDNS AppStream app id.
- Add _launchable_ tag that matches the desktop file name.
- Install the metadata into _metainfo_ directory instead of a deprecated _appdata_ one.
- Add _developer_name_ tag that is required nowadays.
- Add _content_rating_ that is also required by some parsers nowadays.
- Fix screenshot url and wrap it into a proper _image_ tag.
- Fix the _update_contact_ tag to contain actual developer e-mail instead of mine.
@ok2cqr Feel free to review and merge. :-)
Here is another example of a modern AppStream metadata file: https://github.com/gqrx-sdr/gqrx/blob/master/dk.gqrx.gqrx.appdata.xml

Modernize the AppStream metadata
