ok2cqr/cqrlog

help/index.html
Petr, This is the first update. It's also a test to make sure I am using Git correctly.
=> First pass at correcting English usage and typos.

help/h1.html, help/h20.html, help/wkusb.html
One new page updated and a couple of extra fixes to two others
=> English language and typo fixes

src/fLogUploadStatus.lfm
Fix minor spelling error found by Lintian while building the Debian package.
=> Minor spelling fix

src/fNewQSO.pas, src/fPropDK0WCY.lfm, src/fPropDK0WCY.pas
I think I found out now how fonts are set :)
This was requested long time ago. Perhaps it should have it's own settings, but we start with following global fonts.
=> PropDK0WCY uses now preferences/font setting

src/dDXCluster.pas, src/dData.pas, src/fDXCluster.pas, src/fRbnMonitor.pas
This way it can scale in the future
=> dData: use dynamic array for LoTW callsigns

src/ssl_openssl_lib.pas, src/synaser.pas
Ahoj Petre,
mam rad tvoj CQRlog, dekuju za to!
Now I'd finally like to contribute few things.
Have been writing Pascal decades ago, now most of my world is C or C++ or Perl or Python. :)
The first pull request is for a few things I had to change to successfully compile and run it under FreeBSD.
=> FreeBSD changes

src/CHANGELOG, src/fExportPref.lfm, src/fMonWsjtx.lfm, src/fMonWsjtx.pas, src/fNewQSO.lfm, src/fNewQSO.pas
1) Export bugfix: "Choose fields to export" button 'Re/Set All̈́' position conflicts now with appeared (from merge??Was not there before!)  "Most recent entries on top" checkbox. Moved Re/Set-button to same line with OK and Cancel.
2) remote wsjt & Cq-monitor: New features.
src/CHANGELOG updated.
=> remote wsjt & Cq-monitor: + Export bugfix:button 'Re/Set

src/CHANGELOG, src/fMonWsjtx.pas
-CQ-monitor: Calling CQ SOMETEXT without own call (!!!???!) caused porgram halt. Fixed these to NOCALL
=> CQ-Monitor: bugfix

help/h24.html, help/h26.html, help/h27.html, help/h28.html, help/index.html, src/CHANGELOG, src/fNewQSO.pas, src/frCWKeys.lfm, src/frCWKeys.pas
Added voice keying also when FM or AM mode is selected.
Modified CWkeys-form so that buttons execute voice alert if mode is SSB, FM or AM, else execute CW messages (added check of cw interface existence also here, was before only NewQSO).
Updated help files : 
index:
link to CW messages (existing)
link to voice messages (created as h28.html)
Fixed some "prev" & "next" links.
=> Voice keying 

src/fLoTWExport.pas
Makes it easier to understand error reason
=> LoTW export: read and display tqsl output, check exit code

src/fTRXControl.lfm
Thanks. I do not use TRXContol, so it was hard to notice by myself.
- Some band buttons had wrong anchors and were on top of each other - fixed
- power panel caption text was Lazarus default - removed
=> TRXControl: -fixed

src/fImportProgress.pas
Hi! 
I was running my trusty old cqrlog v1.8.1 (time to upgrade huh? :) when I received LoTW qsls for contacts from the same station on same band but on different modes, only one of those QSOs got marked, and in the dialog that showed new QSOs it was registered as SSB but in the log the CW. Tried to find if there where a bug fix for this but when looking in the master branch the bug was still there. The problem is that when the code compares the time in the LoTW adif with the time in the log it uses the LoTW adif time in both places. When the call,band and day query is received it has multiple replies and the code picks the wrong one due to not using the correct time. This PR solves this, but there are more problems left, and I guess there are maybe some historical things why things are …
=> LoTW import bug when having multiple QSOs with same station on same band and day.

src/fAdifImport.pas
Ooops, forgot to test the ADIF import for 12 character MODE, now fixed.
=> added 12 character MODE support on ADIFimport

help/wsjt.html, src/CHANGELOG, src/fDXClusterList.pas, src/fMain.pas, src/fMonWsjtx.pas, src/fNewQSO.pas, src/fQTHProfiles.pas
Rest of sTx fix that was a part of last pull request, but leaved off then to give just the bug fix line.
Fixed some words realy to really on several files.
=> sTx fixes + Some words

src/dUtils.pas, src/fPreferences.lfm, src/fPreferences.pas
- add the feature to select rectangular geometry in the xplanet preferences
- fix typo Membership in preferences tabulator
=> Feature: add geometry rectangular to xplanet preferences

src/fMonWsjtx.pas
Wsjtx v2.0(GA) adds UDP message callsigns angle brackets in some cases . It may cause problems in wb4 database seek and call alert routines of CQ-monitor.
=> Remove angle brackets

src/fMain.lfm, src/fMonWsjtx.lfm, src/fNewQSO.lfm, src/fWorkedGrids.lfm
Some fixes for layout in NewQSO, QSO list, Worked grids, and CQ-monitor.
Mainly anchoring things together rather than keeping them float freely.
Looks good by Martin and me, but all different selections of font sizes are not tested.
=> Layoutfixes1

src/fAdifImport.lfm, src/fAdifImport.pas
- #124 add/repair option for duplicate check during adif import
- translate function names to english
=> improve adif import #124

src/fMonWsjtx.pas
Small bugfix.
Bug appears in very rare conditions.
=> bugfix:Did not clean CQ-monitor when only 1stn in band and qso with that

src/fMonWsjtx.pas, src/fNewQSO.pas
commit f7c965a5cfebd571fc75cad5d2ed068edb74f36f
Date:   Sat Mar 16 09:27:27 2019 +0200
Fix for Fox say RR73
commit 4209b1263970cabc8f7bd10bcb34e51e23cc189e
Date:   Fri Mar 15 16:48:18 2019 +0200
FIX: CQmonitor decode line with 2calls from Fox
=> CQmonitor decode line with 2calls from Fox

src/dData.pas
Frequencies are correct but band label was not.
=> Fix: Database creation error, band=2190M doubled

README.md, docker-build/Dockerfile
Motivated by https://www.cqrlog.com/node/2273 .
=> Provide a way to build with a reproducable Ubuntu build environment.

src/fNewQSO.pas
fixed Right click on call at recent qso list (NewQSO): HamQth search fails #180
=> issue #180 fixed HamQth search fails

src/fNewQSO.lfm
#168 no limit check at newqso fields
- add attribute max length to gui for each field
- add hint (mouse over) for each field
- max length is taken from database varchar length
- trim/cut of overlong strings from online log provider (hamqth,qrz,..) is done
automaticly by attribute max length of gui
=> issue #168 no limit check at newqso fields

src/fNewQSO.pas
=> Fix Switch of logs when Qso list open fails #163

src/cqrlog.lpi, src/fContest.lfm, src/fFilter.lfm, src/fKeyTexts.lfm, src/fPreferences.lfm, src/fPropagation.lfm, src/feQSLDownload.lfm, src/feQSLUpload.lfm
commit 5b63dc19e64d88c91f71af10c5a4d048a2d7d84c
Date:   Mon Nov 25 16:40:57 2019 +0200
calendar, week starts monday
commit 47bf5cf7b2a4d11f0edfc8bc25ff865b4e63651e
Merge: 45dbf70 e9c4c88
Date:   Mon Nov 25 15:51:42 2019 +0200
merge master,fixed
commit 45dbf707f7f2a3497ff5ecbe6f51993d321df40d
Date:   Sat Nov 23 11:17:32 2019 +0200
Contest: help button
commit 0ac1d2b2fbd665f33db87222956ee0a9e751ed01
Date:   Fri Nov 15 17:06:55 2019 +0200
propagation
commit 755a730370db4416c3ba5f919d2ad98e27c9fbc3
Date:   Fri Nov 15 16:09:32 2019 +0200
eqsl op & dnload
commit d9e41a7bdae929b7231f6f44e78ff3028f8dbd47
Author: …
=> Some anchor/layout fixes that make QT5 compilation results look better.

help/contest.html
=> Fix for contest help (Dupecheck)

src/fPreferences.lfm, src/fPreferences.pas
locate wsjt browse button has wrong naming and no  "on click"-action
=> Fixed locate wsjt browse button

src/dUtils.pas
Added another GET parameter to the map call so that also home QTH and a line for the path to the remote station is displayed on the map.
=> Also display path and direction from home QTH

src/fAdifImport.pas, src/fExportProgress.pas, src/fLoTWExport.pas, src/feQSLUpload.pas, src/uADIFhash.pas
- repair MODE and SUBMODE field (some corrupt data was produced)
- CQRLOG Mode=PACKET in ADIF is now PKT (ADIF 3.1.0 conform)
=> Fix ADIF Export for LOTW, EQSL and normal ADIF

src/fAdifImport.pas, src/uADIFhash.pas
- ADIF SUBMODE JS8 and FT4 will be uploaded as MODE JS8/FT4 into cqrlog
- ADIF MODE PKT will be uploaded as MODE PACKET into cqrlog
=> fix ADIF import for JS8, FT4 and PKT

src/dData.pas, src/dUtils.pas, src/fEDIExport.pas, src/fExportProgress.pas, src/fGrayline.pas, src/fMain.pas, src/fMonWsjtx.pas, src/fNewQSO.pas, src/fWorkedGrids.pas
dmUtils.CompleteLoc
- if loc is empty or has odd length it is passed as is to find error later
- if loc is even length it is trim():ed and set to have length of 6 by:
- if length is 2 '44LL' added	( 'KP'    -->  'KP44LL' )
- if length is 4 'LL' added	( 'KP01'  -->  'KP01LL' )
- if length > 6 length is cutted to 6
(means validity of the rest is never checked/used in calculations )
('KP01th23' and 'KP01thereiscat' are both passed as 'KP01th' where)
('KP01thereisacat' is passed as 'KP01thereisacat' = has odd length)
dmUtils.IsLocOK
- calls first dmUtils.CompleteLoc the does simplified test for UpCase(loc)
- accepts only length 6, so all length > 6 and odd length will cause False.
frmWorkedGrids.GridOK
- checks now that length is 4 or 6, then passes to dmUtils.IsLocOK that does the job …
=> Fix for issue AZIM calculation fails #265

src/cqrlog.lpi, src/dDXCluster.pas, src/dUtils.lfm, src/dUtils.pas, src/fDBConnect.lfm, src/fDBConnect.pas, src/fFreq.lfm, src/fFreq.pas, src/fGrayline.pas, src/fNewQSO.pas, src/fPreferences.lfm, src/fPreferences.pas, src/fXfldigi.pas
User was not able to import his adif qso on 443MHz, even when edited 70cm band at preferences/bands/frequencies.
Tested also adif export and it results empty BAND tag when that frequency was used.
Reason is that there exist 3 subroutines having hard coded bandVSfrequency case routines, not using the cqrlog_common.bands database information at all.
This causes problems specially in high bands that have different limits in different Regions.
Changed routines so that memory array is used for bandVSfrequency fetch and array is initialized at start(or log change) and when exit from preferences/bands/frequencies.
Array is small and fast and works better with RBNmonitor as fetch from cqrlog_common.bands database every time it is needed.
While testing new procedure fixed some minor bugs that came …
=> Fix for GetBandFromFreq hard coding

help/h7.html, src/fLoTWExport.pas
dont upload propagation RPT to LoTW (rule violation) #292
=> dont upload propagation RPT to LoTW (rule violation) #292

help/h20.html, src/fNewQSO.pas
fix bug copypaste to gridfield and expand help
=> fix bug copypaste to gridfield and expand help

src/fFilter.lfm, src/fFilter.pas
OH1KH missed to accept my extension. So I PR this to upstream/master :)
=> Adapt valid char check for locator fields

src/fImportLoTWWeb.pas, src/fLoTWExport.pas, src/fMain.pas, src/feQSLDownload.pas, src/feQSLUpload.pas
Replaced synacode's EncodeUrl with dmUtils.EncodeUrlData that can encode ampersand ok. (Needed for passwords issue #305 )
=> Replaced synacode's EncodeUrl

src/fQTHProfiles.lfm
Fixed anchoring and button sizing in QTHprofile form.
Did not show out nice when compiled with QT5
=> Fix for QTH button

src/fMonWsjtx.pas
-speed up connect request send made from CQ monitor with 2xclick
=> Fix wsjtx udp

src/fNewQSO.pas
When any remote is on user should not be able to touch "Offline" checkbox. Now any remote will disable the checkbox.
=> Fix for "Offline" checkbox.

src/fContest.lfm, src/fContest.pas
Now Super check partial works also when call is entered to Contest form like it works with NewQSO entry.
=> Added Super check partial to Contest

src/cqrlog.lpi
I seem to have forgotten this when I added the fChangeOperator unit :(
=> Correct unit count

src/fAbout.lfm, src/fExportProgress.pas
fix wrong if statement. BAND_RX was always exported, even if not wanted or NULL or 0
=> fix band_rx zero problem

src/fSendSpot.pas, src/uVersion.pas
Usr message was saved, but never read causing empty message.
=> Fix for DXSpot/UsrMessage

src/cqrlog.lpr, src/dData.pas, src/uMyIni.pas, src/uVersion.pas
- Cleaned up the function to determine debug level.
- added parameters:
-h --help print short help and exit
-v --version print just version and date and exit
=> Cqrlog start parameters

src/cqrlog.lpi, src/dUtils.pas, src/fContest.lfm, src/fGroupEdit.pas, src/fNewQSO.lfm, src/fNewQSO.pas, src/uVersion.pas
- fixed statusbar placing problem. Issue #383 
- reordered many anchorings of items
- added colors (from DXCluster settings) to counry info (left of qth profiles)
- repositioned QSL and LoTW cfm date displays, added eQSL cfm. They show up now also when entering new qso, if worked before and confirmed.
- Changed "confirmed" colors from red(warning,missing,be aware) to Green (completed,ok, accepted).
- changed "QSL mgr found" color from red(warning,missing,be aware) to Green (completed,ok, accepted).
- Set auto width to DXCC statistic tab grid columns
- Minor reposition in Satellite tab
- repositioned offline checkbox
- added panels to speed buttons. Keeps anchoring always stabile and helps anchoring (when visible, or not)
- Change of buttons Save and Quit text if font>10 to get them fit in …
=> Fixes for NewQSO layout

src/dUtils.pas, src/fAdifImport.pas, src/fExportProgress.pas, src/fLoTWExport.pas, src/fMain.pas, src/fMonWsjtx.pas, src/fNewQSO.pas, src/feQSLUpload.pas, src/uVersion.pas
New release of wsjtx (2.3.0 GA) introduces new mode FST4.
LoTW and eQSL accept FST4 as MFSK submode.
=> Added submode FST4

src/cqrlog.lpi, src/cqrlog.lpr, src/dUtils.pas, src/fAdifImport.pas, src/fRbnMonitor.pas, src/uVersion.pas, src/znacmech.pas
- I think also these regexps should be fixed. RBN monitor fix may even help for seldom happening "empty DX call" lines that happen when following only own callsign. (Not tested as occurs so seldom)
- added znacmech.pas to project. Was "floating" even when used in DXCluster
- some Google translations in znacmech.pas in case it needs lookup some day
commit 587e0b1a2171355c44f4e6acfea83c196a0735aa
Merge: 3789c6b ccac764
Date:   Mon Feb 8 10:26:57 2021 +0200
Merge branch 'master' into regexp and more bug fixes
commit 3789c6b9e43ac2a2d6dfccfac04a1308b85e9917
Date:   Mon Feb 8 08:32:13 2021 +0200
a bug fix
commit a6b703f793a28f84bc7ba80d5294f74982775836
Date:   Sat Feb 6 …
=> Some more regexp fixes and other

src/fCabrilloExport.pas
OK!
Now this should follow Cabrillo specification ( https://wwrof.org/cabrillo/cabrillo-qso-data/ ): 
- fixed the way to extract zipcode and address from preferences/station/zip_city.
Now takes first word as zip and all the rest as address. Supports then multi-word addresses.
- Changed QSO records frequency to be rounded true frequency instead of band generated 
fixed frequency when on <50MHz bands.
- fixed lblCabError printout
commit c6c0107a39dcc1898eaf5150365880598e73e27a
Date:   Mon Feb 15 11:30:30 2021 +0200
Now output fixed by https://wwrof.org/cabrillo/cabrillo-qso-data/ to be true freq under 50MHz and band freq abowe
commit ece8b74ca5d110e31b23327e1a40e755803669da
Date:   Mon Feb 15 …
=> Fixes for Cabrillo export

src/fGroupEdit.lfm, src/fGroupEdit.pas
Add the DOK field to the Group Edit list so that it can be changed during group edit session.
=> Allow DOK edit in Group Edit

docker-build/Dockerfile, src/dData.pas, src/dUtils.pas, src/fCabrilloExport.pas, src/fFreq.pas, src/fMain.pas, src/fNewQSO.pas, src/fPreferences.lfm, src/fPreferences.pas
with current version apt-update is not working any longer - also added changes to alllow automagically configure tzdata
=> Add all uWave bands and fix frequency display issue

src/fGrayline.pas, src/fNewQSO.pas, src/fPreferences.lfm, src/fPreferences.pas
- Fixed own position change in map if my_loc is changed with Ctrl+L at NewQSO
- Fixed own position change in map and NewQSO statusline MyLoc if locator is changed in prefereces/Station
- Added locator validation check for prefereces/Station/Locator
=> Fix for Grayline map

src/fContest.lfm, src/fNewQSO.lfm
- Fixed some MaxLengths in fNewQSO.lfm and fContest.lfm
Caused database error (Abort/OK) if user entered too long strings.
=> Fixes to input max lengths

src/fMonWsjtx.pas, src/fNewQSO.pas, src/uVersion.pas
This fixes FT4 mode monitoring with JTDX program that differs from WSJT-X format
=> Fix for wsjtx-remote with JTDX

help/h1.html, src/fMonWsjtx.pas, src/fNewQSO.pas, src/fXfldigi.lfm, src/fXfldigi.pas, src/uVersion.pas
fldigi remote IPC
- rewritten whole remote connection. Now uses date received from
fldigi as qso start date.
If fldigi sends proper qso start date this should fix problem
that caused when passing UTC midnight while qso. The logged
qso date was set by cqrlog when qso was logged to fldigi.
I.E. Qso end date in case of passing UTC midnight while qso.
- sets now submode as cqrlog mode that can be then properly
encoded back to mode+submode at ADIF exports.
fldigi remote xmlrpc
- added qso start date from fldigi. It also was taken from cqrlog
when qso was logged and had same UTC midnight issue.
- sets now submode as cqrlog mode that can be then properly
encoded back to mode+submode at ADIF exports.
How ever this is true only if fldigi's versions 4.1.20.58 or up. With
older versions of fldigi …
=> Fixes for remotes

src/fPreferences.lfm, src/uVersion.pas
OK, now.
commit 5556ee564c6077c42dc75ef127183488f04648a3
Date:   Fri Jul 1 10:57:31 2022 +0300
Fixed anchor
commit d8de2a29f24215204a9b86587d47e63bbc0364b6
Date:   Thu Jun 30 16:22:34 2022 +0300
fixed preferences/modes layout
commit 627e6b2a3e398d102439f6ea68d56a32fb265790
Date:   Thu Jun 30 15:45:38 2022 +0300
Fix preferences/ROTcontrol
Cleared ROT ID model(1,2) default text "cmbModelRot"
=> Fixes to preferences layout

src/cqrlog.lpi, src/cqrlog.lpr
This PR only adds unit fDBerror to project for easer finding with Laz GUI
=> Add unit fDBError

src/fPreferences.lfm, src/uVersion.pas
Changed max value of all passbands to be 100kHz that suits
better to modern rigs than previous 3000/6000 and makes
no harm having it "high enough".
=> Fix for preferences/modes

Makefile
Closes #570.
@ok2cqr Feel free to review and merge.
=> fix: desktop icons installation
